name: 'GitHub Actions CloudFlare2DNSPod Bot'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/16 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: 'Install dependencies'
        run: pip install -r requirements.txt
      
      # 添加调试步骤（临时）
      - name: Debug environment variables
        run: |
          echo "CONFIG length: ${#CONFIG}"
          echo "DOMAINS length: ${#DOMAINS}"
          echo "PROVIDER length: ${#PROVIDER}"
      
      - name: 'run cf2dns'
        env:
          CONFIG: ${{ secrets.CONFIG }}
          DOMAINS: ${{ secrets.DOMAINS }}
          PROVIDER: ${{ secrets.PROVIDER }}
        run: python cf2dns_actions.py
